document.addEventListener('DOMContentLoaded', () => {
    const urlParams = new URLSearchParams(window.location.search);
    const songId = parseInt(urlParams.get('songId'));

    const songs = [
        {
            id: 1,
            title: "I'm Missing You - Sunjae (선재)",
            image: "../images/songs2.jpg",
            description: "I'm Missing You oleh Sunjae adalah lagu yang ditampilkan oleh Sunjae (선재), yang menggambarkan kerinduan yang mendalam dan emosional seseorang terhadap seseorang yang mereka cintai, dengan lirik yang penuh makna dan melodi yang memikat. Lagu ini dirilis pada tanggal 15 Februari 2020....",
            lyrics: [
                "아직 모르고 있죠 그댄",
                "얼마나 특별한지",
                "당신의 맘에", 
                "이런 내가 닿길 바래",
                "조금 더 깊어져가 내가",
                "그대와 함께할수록 나",
                "I'm missing you",
                "Waiting for you",
                "내 맘이 그대를 향해 있는 걸요",
                "I'm missing you",
                "Waiting for you",
                "그댈 오늘도 기다려요",
                "고민이 많아져요 이젠",
                "하루 온종일 그대 생각만 하는 나",
                "I'm missing you",
                "Waiting for you",
                "내 맘이 그대를 향해 있는 걸요",
                "I'm missing you",
                "Waiting for you",
                "그댈 오늘도 기다려요",
                "언제나 내 곁을 지켜 주었던 그댈",
                "놓치고 싶지 않아요",
                "정말",
                "I'm missing you",
                "Waiting for you",
                "내 맘이 그대를 향해 있는 걸요",
                "I'm missing you",
                "Waiting for you",
                "그댈 오늘도 기다려요",
                "그댈 오늘도 기다려요"
            ],
            audio: "../audios/sun jae snzae i'm missing you ost true beauty part 4.mp3"
        },
        {
            id: 2,
            title: "Fall In You - Ha SungWoon",
            image: "../images/songs1.jpg",
            description: "Fall In You oleh Ha SungWoon adalah lagu pop yang menyentuh tentang jatuh cinta dengan lirik yang menggambarkan perasaan yang intens dan melodi yang mengalun mengalir. Dirilis pada tanggal 5 Maret 2021, lagu ini dibawakan oleh Ha SungWoon, dan berhasil menciptakan momen emosional bagi pendengarnya....",
            lyrics: [
                "용기가 나지 않아서 그래",
                "혹시 너에게 부담일까 봐",
                "매번 마음 졸이며 그대를",
                "사랑하고 있어 나",
                "Fall in you",
                "나 이제야 알게 됐죠",
                "Fall in you",
                "널 기다리고 있어요",
                "Fall in you",
                "그댄 내 운명이죠",
                "나의 별이 되어줄 한사람",
                "내 모든 걸 주고픈 한사람",
                "그대",
                "그대",
                "그대 생각에 빠져살아요",
                "혹시 내 맘을 알아줄까 봐",
                "항상 가까운 곳에 있는 날",
                "이젠 알아봐 주세요",
                "Fall in you",
                "나 이제야 알게 됐죠",
                "Fall in you",
                "널 기다리고 있어요",
                "Fall in you",
                "그댄 내 운명이죠",
                "나의 별이 되어줄 한사람",
                "제가 너무 늦진 않았나요",
                "상처받을까 봐",
                "내가 겁이 났나 봐요",
                "처음이라서 이제야 깨달았죠",
                "그대가 나의 사랑이란 걸",
                "Fall in you",
                "나 이제야 알게 됐죠",
                "Fall in you",
                "널 기다리고 있어요",
                "Fall in you",
                "그댄 내 운명이죠",
                "나의 별이 되어줄 한사람",
                "내 모든 걸 주고픈 한사람",
                "그대"
            ],
            audio: "../audios/HA SUNG WOON - Fall in You (OST True Beauty Part.6).mp3"
        },
        {
            id: 3,
            title: "Sacrifice - Han Seung-Woo (한승우)",
            image: "../images/fame.jpg",
            description: "Sacrifice oleh Han Seung-Woo (한승우) adalah lagu solo yang dibawakan oleh Han Seung-Woo (한승우), mantan anggota grup K-pop Victon, yang menampilkan vokal yang mendalam dan lirik yang menyentuh, dirilis pada tanggal 10 Agustus 2020....",
            lyrics: [
                "Yeah ooh uh",
                "봐도 봐도 날 미치게 하는 type",
                "어딜 봐도 흠잡을 곳 없이 shine",
                "널 가만두지 않아 다들 그래 아마",
                "딱 잘라 말해 좀 월등한 아이",
                "Sometimes I can feel your eyes",
                "뭔가 있을지도 몰라 상상해 all night",
                "더 깊어져 가",
                "널 알면 알수록 벗어나질 못해",
                "숨겨둬 네 그림자도",
                "달콤한 네 속삭임도",
                "오직 내게만 비춰 줘 날 끌어당겨 줘",
                "It's better if you never go",
                "I just gotta sacrifice",
                "날 내버려 둬 I like it now",
                "Oh she is mine",
                "오늘부터 drive me crazy more and more",
                "Oh sacrifice 내 모든 걸 가져가",
                "집착해 네 생각보다 난 좀 뻔뻔해 미쳐가",
                "But you're not ready yet",
                "난 또 괜찮다고 해 이렇게 하루를 접어도",
                "Wanna be with you all the time",
                "혼자 두기는 싫어 좀 불안해 oh baby",
                "더 짙어져 가",
                "날이 지날수록 벗어나질 못해",
                "숨겨둬 네 그림자도",
                "달콤한 네 속삭임도",
                "오직 내게만 비춰 줘 날 끌어당겨 줘",
                "It's better if you never go",
                "I just gotta sacrifice",
                "날 내버려 둬 I like it now",
                "Oh she is mine",
                "오늘부터 drive me crazy more and more",
                "I just gotta sacrifice",
                "I'm gonna get you baby",
                "I need you to know me",
                "널 더 원해 is the point of sacrifice",
                "거리를 좁혀 다가가 ah",
                "널 좀 더 진하게 그려봐 (그려봐)",
                "넘어와 준비가 돼 있어",
                "난 여기 서 있어 stay with me all the time",
                "거리를 좁혀 다가가",
                "널 좀 더 진하게 그려봐",
                "넘어와 준비가 돼 있어 wow",
                "Sacrifice",
                "I just gotta sacrifice",
                "날 내버려 둬 I like it now",
                "Oh she is mine",
                "오늘부터 drive me crazy more and more",
                "I just gotta sacrifice (oh oh)",
                "I'm gonna get you baby (oh oh)",
                "I need you to know me (oh oh)",
                "널 더 원해 is the point of sacrifice",
                "I just gotta sacrifice"
            ],
            audio: "../audios/Han Seung Woo - Sacrifice [129 kbps] (1).mp3"
        },
        {
            id: 4,
            title: "UN Village - Baekhyun (백현)",
            image: "../images/citylight.jpg",
            description: "UN Village oleh Baekhyun (백현) adalah lagu solo yang dirilis oleh Baekhyun, anggota dari grup idola Korea Selatan EXO, pada tanggal 10 Juli 2019. Lagu ini merupakan bagian dari album mini solo pertamanya yang berjudul City Lights. Dengan lirik yang memikat dan melodi yang adiktif, UN Village menampilkan vokal yang mendalam dan kualitas produksi yang tinggi, membawa pendengar dalam perjalanan melalui suasana malam yang misterius di kawasan UN Village di Seoul.",
            lyrics: [
                "Navigation 독서당어린이공원으로",
                "누르고 엑셀을 밟아",
                "나만 알고 있던 그곳은 now",
                "모두가 올라가려 하겠지",
                "어디서든지, everywhere, anywhere",
                "얼마든지 보여",
                "Girl, we need to be romantic함이",
                "필요한 시점이야",
                "이미 알고 있었다고 해도",
                "처음 느끼는 기분으로",
                "널 리드할게, lean on me",
                "나에게만 너의 특별한 시간을",
                "보낼 수 있는 자격이 있단 걸",
                "난 알아, I know that I know that I know",
                "그래 우린 지금",
                "한남동 UN Village hill",
                "언덕에서 달을 보며",
                "You and me, hmm, yeah",
                "UN Village hill, ayy",
                "나란히 우린 달을 보며",
                "You and me, relax and chillin', ayy, yeah",
                "완벽한 모습을 너에게 보이진 않을 거야",
                "지금 이 순간만큼은 모든 걸",
                "흘러가는 대로 부는 곳으로 바람이",
                "사랑을 속삭일 때 난 원해",
                "무심하던 네 눈빛이 날 사랑한다",
                "말을 하는 순간을",
                "이미 알고 있었다고 해도",
                "처음 느끼는 기분으로",
                "널 리드할게, lean on me",
                "나에게만 너의 특별한 시간을",
                "보낼 수 있는 자격이 있단 걸",
                "난 알아, I know that I know that I know",
                "그래 우린 지금",
                "한남동 UN Village hill",
                "언덕에서 달을 보며",
                "You and me, hmm, yeah",
                "UN Village hill, ayy",
                "나란히 우린 달을 보며",
                "You and me, relax and chillin', ayy, yeah",
                "Rolling, rolling, rolling, hills",
                "구불구불한 언덕을 따라",
                "Rolling, rolling, rolling, hills",
                "오르다 보면 고장 난 가로등 불",
                "하나가 보이면 그 아래에서 light를 꺼",
                "이곳은 충분히 너 하나로도 환하니까",
                "한남동 UN Village hill",
                "언덕에서 달을 보며",
                "You and me, hmm, yeah",
                "UN Village hill, ayy",
                "나란히 우린 달을 보며",
                "You and me, relax and chillin', ayy, yeah",
                "Oh, hmm",
                "Oh, ayy"
            ], 
            audio: "../audios/Baekhyun EXO - UN Village.mp3"
        },
        {
            id: 5,
            title: "HEAVEN - AB6IX (에이비식스)",
            image: "../images/newhope.jpg",
            description: "HEAVEN oleh AB6IX (에이비식스) adalah lagu K-pop yang dirilis pada 21 November 2022, menggabungkan beat elektronik yang energik, vokal kuat, rap dinamis, koreografi menarik, dan video musik estetis untuk menciptakan suasana kebahagiaan dan keindahan seolah-olah berada di surga...",
            lyrics: [
                "Oh, oh, oh, oh, oh, oh",
                "Oh, oh, oh, oh, oh, oh",
                "I've been going down on circle",
                "향기 가득했던 day and night",
                "저 달마저 널 환히 비추고",
                "빛을 따라 우린 서로를 바라봐",
                "그저 그런 관계 사이 속",
                "따뜻했던 너의 품에서 yeah",
                "Want your kiss 너의 온기",
                "난 숨을 쉬어 when you are next me",
                "넌 나의 sun 어두운 내 삶을 비춰",
                "Dance for two 너와 함께 step을 맞춰",
                "'Cause you're my star 저 별빛처럼",
                "항상 내 곁에 있어줘",
                "Baby, if you're waiting for me in dawn",
                "오래 기다리지 않게 내가 먼저 다가갈게 oh",
                "항상 내 길을 밝혀준 너",
                "무너뜨려 나의 demons (Yeah)",
                "이젠 느낄 수 있어 너란 heaven",
                "Oh, oh, oh, oh, oh, oh",
                "Oh, oh, oh, oh, oh, oh",
                "따스히 감싸 안아줘 to your heaven",
                "난 이미 천국에 갇혀 매일 아침 뜨는 해를 봐",
                "널 기다리며 밤을 지새워도 시간은 가지 않아",
                "이미 정해놓은 별자리 그 위를 따라 걸어가",
                "기다림이 그리움으로 바뀌기 전에 (바뀌기 전에)",
                "기대도 돼 내가 힘이 된다면",
                "Pretty girl 항상 곁을 내줄게",
                "'Cause you're my star 저 별빛처럼",
                "찬란하게 비출게",
                "Baby, if you're waiting for me in dawn",
                "오래 기다리지 않게 내가 먼저 다가갈게 oh",
                "항상 내 길을 밝혀준 너",
                "무너뜨려 나의 demons (Yeah)",
                "이젠 느낄 수 있어 너란 heaven",
                "Oh, oh, oh, oh, oh, oh",
                "Oh, oh, oh, oh, oh, oh",
                "따스히 감싸 안아줘 to your heaven",
                "Baby, we could dance all night",
                "저무는 태양 아래 두 그림자 yeah",
                "Wanna kiss, wanna love, love you more and more",
                "아득한 구름 속을 우린 날아가",
                "길을 잃고 헤맨 시간도",
                "상처뿐인 과거의 기억도",
                "이젠 두렵지 않아",
                "우리 함께 있다면 여긴 heaven",
                "Oh, oh, oh, oh, oh, oh",
                "Oh, oh, oh, oh, oh, oh",
                "너란 heaven",
                "Oh, oh, oh, oh, oh, oh",
                "Oh, oh, oh, oh, oh, oh",
                "우리 함께 있다면 여긴 heaven"
            ], 
            audio: "../audios/AB6IX - HEAVEN [320 kbps].mp3"
        },
        {
            id: 6,
            title: "Wishes - Jamie Miller",
            image: "images/song3.jpg",
            description: "Wishes  oleh Jamie Miller adalah sebuah lagu yang diciptakan oleh Jamie Miller, yang menyajikan pesan tentang harapan dan impian melalui lirik-lirik yang penuh emosi dan melodi yang menarik, merilis pada tanggal 12 Maret 2021...",
            lyrics: [
                "I'm throwing out the page I found",
                "The memory 'bout you and I",
                "There's a time I dreamed about",
                "The place we'll go on a summer night",
                "So take me to your deepest heart",
                "Now I really need proof to go on",
                "'Cause my life goes dark",
                "When I know that I can never be your love, oh-oh",
                "Wish we never talked",
                "Wish we never saw",
                "But now I know you're just too far",
                "To catch you with my arms",
                "Wish I never met you",
                "Wish I never touched your hand",
                "On the day I really thought you are",
                "The only one that I could ever really love",
                "I'm not a person that believe",
                "About the things that people talk",
                "But the things you said, they made my world",
                "I never doubted you were wrong, ooh-ooh",
                "So take me to your deepest heart",
                "Now I really need proof to go on",
                "'Cause my life goes dark",
                "When I know that I can never be your love",
                "Oh-oh-oh-oh",
                "Wish we never talked",
                "I wish we never saw",
                "But now I know you're just too far",
                "To catch you with my arms",
                "I wish I never met you",
                "I wish I never touched your hand",
                "On the day I really thought you are",
                "The only one that I could ever really love",
                "Just tell me that I'm wrong",
                "Or say anything at all",
                "I don't care if it's true or false, no",
                "Don't tell me your excuses",
                "Was the love we had honest",
                "Was it ever true?",
                "I wish we never talked",
                "I wish we never saw",
                "But now I know you're just too far",
                "To catch you with my arms",
                "I wish I never met you",
                "I wish I never touched your hand",
                "The day I really thought you are",
                "The only one that I could ever really love"
            ], 
            audio: "../audios/Jamie Miller - Wishes (Snowdrop OST Part.4) [320 kbps].mp3"
        },
        {
            id: 7,
            title: "SURREAL(Alternative Rock Mix) - AB6IX (에이비식스)",
            image: "../images/newhope.jpg",
            description: "SURREAL(Alternative Rock Mix) oleh AB6IX (에이비식스) adalah lagu karya AB6IX (에이비식스) yang menggabungkan elemen-elemen rock alternatif dengan gaya musik pop mereka yang khas, menciptakan atmosfer yang unik dan misterius. Lagu ini dirilis pada tanggal 5 Mei 2024....",
            lyrics: [
                "Oh",
                "눈 감았다 뜨면 모든 게 다 새로워 보여",
                "큰 숨을 삼키면 달콤함에 정신을 잃어 oh",
                "몸을 파고드는 황홀한 이 감각",
                "이미 나는 중독되어 벗어날 수 없어",
                "꿈꾸던 날들이 초라해질 만큼",
                "그렇게 넌 아름다워",
                "너를 본 그 순간",
                "다른 세상이 보여 난 (다른 세상이 보여 난)",
                "현실보다 더 선명한 꿈",
                "그 속의 너와 나 (설명할 수가 없어 이 느낌)",
                "Surreal",
                "어느 미친 예술가의 그림처럼",
                "알 수 없는 아름다움에 끌려",
                "Surreal",
                "홀린 듯이 네게 빠져들어 점점",
                "또 다른 차원 속의 네 모습은",
                "Surreal",
                "현실과 꿈의 경계를 넘나들어",
                "보기 전까지 믿지 않지",
                "이 느낌 바로 전에 느꼈던 감정은",
                "알 수가 없지",
                "전과 자꾸 다른 모습을 보이는 나 왠지 익숙해",
                "이건 아마 다 운명인 듯 정해져 있던 dejavu",
                "나를 좀 더 높은 곳으로 데려가",
                "이제 나는 예전으로 돌아갈 수 없어",
                "내 상상력이 우스워질 만큼",
                "그렇게 넌 아름다워",
                "너를 본 그 순간",
                "다른 세상이 보여 난 (다른 세상이 보여 난)",
                "현실보다 더 선명한 꿈",
                "그 속의 너와 나 (설명할 수가 없어 이 느낌)",
                "Surreal",
                "어느 미친 예술가의 그림처럼",
                "알 수 없는 아름다움에 끌려",
                "Surreal",
                "홀린 듯이 네게 빠져들어 점점",
                "또 다른 차원 속의 네 모습은",
                "Surreal",
                "너라는 덫에 일부러 발을 들여",
                "닿는 순간 직감은 확신이 되고",
                "딴 세상으로 인도하는 널 믿지 난",
                "이게 내 현실 네가 있는 곳 이곳이 진실",
                "Yeah 눈 감았다 뜬 모습들은 이미 내게",
                "모두 다 비현실",
                "너의 곁에 닿는 그 순간",
                "눈부신 별들이 비처럼 내려와",
                "네게 빠져 하루 종일 유영하다가도",
                "저 높은 하늘로 언제나 날 데려다줘",
                "완벽을 넘어선 새로운 차원이야 넌",
                "My universe",
                "너를 본 그 순간",
                "다른 세상이 보여 난",
                "현실보다 더 선명한 꿈",
                "그 속의 너와 나 (설명할 수가 없어 이 느낌)",
                "Surreal",
                "어느 미친 예술가의 그림처럼",
                "알 수 없는 아름다움에 끌려",
                "Surreal",
                "홀린 듯이 네게 빠져들어 점점",
                "또 다른 차원 속의 네 모습은",
                "Surreal",
                "Surreal",
                "Surreal",
                "Surreal"
            ], 
            audio: "../audios/AB6IX - (SURREAL) (Alternative Rock Mix.) [320 kbps].mp3"
        },
        {
            id: 8,
            title: "SALUTE - AB6IX (에이비식스)",
            image: "../images/salute.jpg",
            description: "SALUTE oleh AB6IX (에이비식스)  adalah lagu dari boyband Korea Selatan, AB6IX (에이비식스), yang dirilis pada tanggal 29 Juni 2020. Lagu ini menampilkan kombinasi energi yang menggembirakan dan lirik yang menginspirasi, menciptakan suasana yang membangkitkan semangat untuk merayakan pencapaian dan menghadapi tantangan dengan keyakinan....",
            lyrics: [
                "Ah ah ah ah, ah ah ah",
                "주목해 내 손짓 하나에 이리로 저리로 move",
                "생각보다 넌 좀 easy game (game, game, game)",
                "명심해 잘못 건드리면 얼레리꼴레리 넌",
                "나에게는 그저 piece of cake",
                "(What you waiting for)",
                "Yeah yeah",
                "아무리 떠들고 찾아봐라 옥의 티",
                "우린 이미 한 배를 다 타타타타타",
                "Eh 미리 말했잖아 우린 여기 모든 걸 betting",
                "한 목소리로 외침 what",
                "노력해 노력해 계속 working",
                "들어 손들어 손들어 트로피",
                "No pain, no gain 죽으란 법 없지",
                "늘 그래왔듯 우린 다른 길을 찾지",
                "일렬로 맞춰 다 준비를 해",
                "붉은색 빛으로 물들여",
                "내 안에 남은 것이 없도록 쏟아내 후횐 없게",
                "Oh oh 목청이 터져라 외쳐 my name",
                "넘어져도 다시 일어나네",
                "If you are ready to call on my name",
                "오른손 들어",
                "Salute",
                "Only yes allowed in here",
                "Brr ta ta ta, salute, ah",
                "Only yes allowed in here",
                "(AB6IX) salute",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Only yes allowed in here",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Salute",
                "오른쪽 salute sign 우리의 connection",
                "아무도 모르게 하는 비밀스러운 action",
                "You and I babe, in this brand new avenue",
                "새로운 길 개척",
                "I'm going my way 난 나만의 길로",
                "너는 너나 해 간섭은 별로",
                "You're trapped in my zone 다른 예는 없듯이",
                "출구는 없어",
                "There ain't no answer speech",
                "일렬로 맞춰 다 준비를 해",
                "붉은색 빛으로 물들여",
                "내 안에 남은 것이 없도록 쏟아내 후횐 없게 oh oh",
                "목청이 터져라 외쳐 my name",
                "넘어져도 다시 일어나네",
                "If you are ready to call on my name",
                "오른손 들어",
                "Salute",
                "Only yes allowed in here",
                "Brr ta ta ta, salute, ah",
                "Only yes allowed in here",
                "(AB6IX) salute",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Only yes allowed in here",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Salute",
                "I'll show you my paradise",
                "출구가 없어 no way out",
                "이제 막 시작인걸",
                "We got long way to go baby",
                "기다리다 놓치고 후회하지는 않게",
                "The only way is to say yes",
                "Oh eh oh eh oh eh oh oh oh",
                "Oh eh oh eh oh eh oh oh oh",
                "Only yes allowed in here",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Come and get me, come and get it",
                "Salute"
            ], 
            audio: "../audios/AB6IX - SALUTE [320 kbps].mp3"
        },//
        {
            id: 9,
            title: "Not Too Late - ATEEZ(에이티즈)",
            image: "../images/zeropart3.jpg",
            description: "Not Too Late oleh ATEEZ (에이티즈) adalah sebuah lagu dari boy band Korea Selatan, ATEEZ (에이티즈), yang memadukan elemen-elemen musik pop dan hip-hop dengan vokal yang kuat dan energik, mengeksplorasi tema-tema tentang keberanian dan ketabahan dalam menghadapi tantangan kehidupan. Lagu ini dirilis pada tanggal 28 Januari 2023.",
            lyrics: [
                "어두워 이곳은",
                "차갑게 시들하고",
                "기댈 곳 하나 없는",
                "외로운 이곳",
                "무엇도 안 보여 난",
                "어디로 가야 하나",
                "나 홀로 남아버린",
                "외로운 이곳",
                "Is anyone out there 들리시나요",
                "내 읊조리는 고독이 들리시나요",
                "Oh please",
                "답을 알려줘요",
                "나 홀로 남아 벗어날 수 없는 이유",
                "Too late, too late",
                "Oh, not too late",
                "이유가 있을 거라 난 믿어",
                "It's too late, too late",
                "Oh, not too late",
                "언젠가 마주할 빛을 찾아",
                "I know it's not my fault",
                "잘 살아 멀쩡해 나 잘 먹고 잘살아",
                "걱정하지 말라고 엄마 아빠나 잘 살아",
                "그래 맞아 행복해 내가 선택한 거 맞아",
                "그런데도 가끔 이렇게 허전할 때는 말이야",
                "텅 빈 방 모서리에 붙어 울기도 해",
                "대상 없는 아무개를 향해 하는 고해",
                "다 괜찮을 거야, 다 괜찮을 거야",
                "확신 없는 메아리 자장가를 대신해",
                "Is anyone out there 들리시나요",
                "내 읊조리는 고독이 들리시나요",
                "Oh please",
                "답을 알려줘요",
                "나 홀로 남아 벗어날 수 없는 이유",
                "Too late, too late",
                "Oh, not too late",
                "이유가 있을 거라 난 믿어",
                "It's too, late too late",
                "Oh, not too late",
                "언젠가 마주할 빛을 찾아",
                "한 두 번이면 되잖아",
                "그만 날 꺼내줘요",
                "흔들리고 싶지 않아",
                "이러다 사라지겠어",
                "죽이고 살리고 미치게 아련하게 하지 마",
                "미련 없이 버리고 싶으니까요",
                "보이는 거야, 왜 실낱같은 희망이",
                "다시 한번 믿어볼까 하는 환상이",
                "현실이 될까 봐 그 희망을",
                "못 이겨서 다시 살아가 보려 해 난",
                "Too late, too late",
                "Oh, not too late",
                "이유가 있을 거라 난 믿어",
                "It's too late, too late",
                "Oh, not too late",
                "언젠가 마주할 빛을 찾아 (ah)",
                "It's not too late, oh",
                "언젠가 마주할 빛을 찾아"
            ], 
            audio: "../audios/ATEEZ - (Not Too Late) [320 kbps].mp3"
        },
 
        {
            id: 10,
            title: " Eternal Sunshine - ATEEZ (에이티즈)",
            image: "../images/zeropart3.jpg",
            description: "Eternal Sunshine oleh ATEEZ (에이티즈) adalah sebuah lagu dari boy band Korea Selatan, ATEEZ (에이티즈), yang memadukan elemen-elemen musik pop dan hip-hop dengan vokal yang kuat dan energik, mengeksplorasi tema-tema tentang keberanian dan ketabahan dalam menghadapi tantangan kehidupan. Lagu ini dirilis pada tanggal 28 Januari 2023.",
            lyrics: [
                "단 하나의 기억",
                "남길 수 있다면 (oh)",
                "넌 어떤 순간을 기억하고 싶니",
                "난 하나의 기억을 남긴다면 (oh)",
                "지금 이 순간일 거야",
                "What you want my treasure, hey, fix on",
                "아름다운 풍경이길 바라",
                "뭘 원하는지 속삭여줘 내게 더",
                "약속할 게 I'll get you a star",
                "꿈꾸던 그곳 네 앞에 와있을 거야",
                "I'm coming up to you, look at my heart",
                "Maybe 내 색깔은 보랏빛 밤",
                "잔잔한 파도의 노래를 담아",
                "찾아온 8월의 크리스마스",
                "스쳐 가는 시간 속",
                "너와 내가 만들어갈",
                "끝나지 않을 축제",
                "어둠마저 잠든 밤",
                "영원의 태양을 띄워",
                "(Alright, turn it up, let's make it louder)",
                "Can't stop the feeling",
                "찬란하게 반짝임을 느낀 순간",
                "(Oh oh) you know it (oh oh yeah)",
                "Don't stop believin'",
                "영원보다 멀리 기억하고 싶어",
                "We shine like eternal sunshine",
                "Oh so bright",
                "We shine like eternal sunshine",
                "Ah, we shine like eternal sunshine (ahaha)",
                "One 나를 생각해줘 errday",
                "Two 따라 따라 불러봐 이 노래를",
                "Three 우리는 모든 순간에다 건배해",
                "Okay 치즈 oh yeah",
                "피터팬의 젊음, 그리고 뫼비우스의 띠도",
                "영원한 건 많지",
                "그 중 으뜸은 우리고",
                "So, tell me baby, oh tell me baby",
                "Boy, I can't let you go",
                "스쳐 가는 시간 속",
                "너와 내가 만들어갈",
                "끝나지 않을 축제",
                "어둠마저 잠든 밤",
                "영원의 태양을 띄워",
                "(Alright, turn it up, let's make it louder)",
                "Can't stop the feeling",
                "찬란하게 반짝임을 느낀 순간",
                "(Oh oh) you know it (oh oh yeah)",
                "Don't stop believin'",
                "영원보다 멀리 기억하고 싶어",
                "We shine like eternal sunshine",
                "다 여기 모여 춤을 춰",
                "Let's keep on moving",
                "오늘 밤 잊지 못할 춤을 춰",
                "Let's keep on moving",
                "다 같이 left and right",
                "Everybody clap your hands",
                "다 같이 left and right",
                "Everybody hands up in the air",
                "Can't stop the feeling",
                "찬란하게 반짝임을 느낀 순간",
                "Oh you know it (you're my shining star)",
                "Don't stop believin'",
                "영원보다 멀리 기억하고 싶어",
                "We shine like eternal sunshine",
                "Oh so bright",
                "We shine like eternal sunshine",
                "Oh yeah (hey)",
                "We shine like eternal sunshine"
            ], 
            audio: "../audios/ATEEZ - Eternal Sunshine [320 kbps].mp3"
        },
        {
            id: 11,
            title: "All For You - CIX (씨아이엑스)",
            image: "../images/CIXAllForYou.jpg",
            description: "All For You oleh CIX (씨아이엑스) adalah lagu dari boyband Korea Selatan, CIX (씨아이엑스), yang menggabungkan elemen-elemen pop dan hip-hop dengan vokal yang kuat, menciptakan suasana yang enerjik dan menghibur. Lagu ini dirilis pada tanggal 23 Agustus 2021....",
            lyrics: [
                "Hey you",
                "I know we haven't talked in a while",
                "(Aye yo aye yo aye yo aye yo)",
                "You doin' ok?",
                "I'll be here for you",
                "(Aye yo aye yo aye yo aye yo)",
                "Are you doin' alright?",
                "Tell me",
                "変わりはない?",
                "Show me, uh",
                "季節変わり 月日過ぎたけど",
                "この気持ちは",
                "変わらない",
                "教えて君の story, yeah",
                "喜び 悲しみ everything, uh",
                "僕の想いの数 365",
                "伝えきれないよ",
                "太陽見て君の笑顔思い出す",
                "1日が君で beautiful",
                "「また明日」言える様になる",
                "Thinking about, thinking about you",
                "繋がってる二人 yeah",
                "届けたい想い溢れる",
                "Oh all for you",
                "伝えたい話増えてく",
                "All for you",
                "また会えるよ",
                "No need to worry",
                "その日来るまで",
                "信じて待って (hey)",
                "離れても",
                "(Aye yo aye yo aye yo aye yo)",
                "心寄り添う",
                "(Aye yo aye yo aye yo aye yo)",
                "遠くても",
                "耳澄ませば",
                "I'll be right here all for you",
                "Yeah また埋く瞳で",
                "僕の事すぐ照らして",
                "君見つけるために",
                "Let me be the one you see",
                "会えなくても all good (all good!)",
                "心にいる all you (all you!)",
                "映りたい your eyes",
                "そんな当たり前",
                "もうすぐ with you",
                "星を見て君の笑顔思い出す",
                "1日が君で終わっていく",
                "同じ空の下結ばれ",
                "Feelin' for, feelin' for you",
                "繋がってる二人 yeah",
                "届けたい想い溢れる",
                "Oh all for you",
                "伝えたい話増えてく",
                "All for you",
                "また会えるよ",
                "No need to worry",
                "その日来るまで",
                "信じて待って (hey)",
                "君にしか涙は",
                "見せたくないよ",
                "次会う時まで",
                "溜めておくから",
                "でもその笑顔見れば",
                "喜びに変わる",
                "後少しだけ",
                "And I'll be with you",
                "届けたい想い溢れる",
                "Oh all for you",
                "伝えたい話増えてく",
                "All for you",
                "また会えるよ",
                "No need to worry",
                "その日来るまで",
                "信じて待って (I got you!)",
                "離れても",
                "(Aye yo aye yo aye yo aye yo)",
                "心寄り添う",
                "(Aye yo aye yo aye yo aye yo)",
                "遠くても",
                "耳澄ませば",
                "I'll be right here all for you"
            ], 
            audio: "../audios/CIX - All For You [129 kbps].mp3"
        },
        // Add more songs here
    ];

    const song = songs.find(s => s.id === songId);

    if (song) {
        document.getElementById('song-title').textContent = song.title;
        document.getElementById('song-image').src = song.image;
        document.getElementById('song-description').textContent = song.description;
        const style = document.createElement('style');
        style.textContent = '#song-description { text-indent: 40px; }';
        document.head.appendChild(style);
        document.getElementById('song-lyrics').innerHTML = song.lyrics.join('<br>');
        document.getElementById('audio-source').src = song.audio;
        document.getElementById('song-audio').load();

    } else {
        document.getElementById('song-title').textContent = 'Song not found';
        document.getElementById('song-description').textContent = "";
        document.getElementById('song-lyrics').innerHTML = "";
    }
});
